name: Idena Arm


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go arm
        run: wget https://go.dev/dl/go1.17.7.linux-armv6l.tar.gz &&  sudo tar -C /usr/local -xzf go1.17.7.linux-armv6l.tar.gz && rm go1.17.7.linux-armv6l.tar.gz
      - name: Go path
        run: echo "PATH=$PATH:/usr/local/go/bin GOPATH=$HOME/go" >> ~/.profile && source ~/.profile
      - name: Build Arm
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm CC=arm-linux-gnueabihf-gcc go build -ldflags "-X main.version=0.28.5"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: builds/${{ env.ASSET_NAME }}
